# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Carlo Fusco and Leonardo Restivo
"""Tests for Unit 5: Consultant Agent and Ledger.

Synthetic data generation assumptions
--------------------------------------
- All ``project_root`` fixtures are fresh ``tmp_path``-based directories.
  The ``.debrief/briefs/`` subdirectory is created by the test fixture
  wherever the function under test requires it to pre-exist; otherwise
  the function is expected to create it itself.
- Slide brief dicts are minimal valid dicts containing exactly the nine
  required fields: ``slug``, ``title``, ``content_goal``,
  ``visual_approach``, ``visual_pattern``, ``rhetorical_role``,
  ``design_invariants``, ``user_recommendations``, ``group_id``.
- Valid ``rhetorical_role`` values used in tests are drawn from the
  canonical set: ``hook``, ``ethos``, ``pathos``, ``logos``,
  ``synthesis``, ``recap``, ``transition``.
- Invalid rhetorical roles use arbitrary strings not in the allowed set
  (e.g. ``"intro"``, ``"conclusion"``, ``"bad_role"``).
- Slug values used in tests conform to ``^[a-z][a-z0-9_]{0,49}$`` and
  do not end with ``_`` unless the test is specifically probing slug
  validation failure.
- Group IDs used in tests conform to ``^(group|backup)_\\d{2}$``
  (e.g. ``"group_01"``, ``"backup_01"``) unless the test is probing
  group-ID validation failure.
- Ledger entries are written with role ``"consultant"`` or ``"user"``;
  content is a short ASCII string.  Timestamps are generated by the
  implementation at call time and are only checked structurally (non-empty
  string).
- Compaction tests build a ledger with exactly 101 JSONL lines (i.e.
  ``> 100``) by calling ``append_ledger_entry`` in a loop.  This is one
  more than the 100-entry trigger threshold in BC-5.5.
- Archive naming tests pre-create ``ledger_compact_001.jsonl`` to verify
  that the second compaction produces ``ledger_compact_002.jsonl``.
- Atomic write behaviour for ``write_slide_brief`` and
  ``write_group_manifest`` is verified by checking that no ``.tmp``
  sibling exists after a successful call and that the target file contains
  valid JSON.
- ``dispatched_at`` in the manifest is only checked to be a non-empty
  string; exact ISO-8601 format is not re-verified here.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from ledger import (
    append_ledger_entry,
    compact_ledger,
    validate_slide_brief,
    write_group_manifest,
    write_slide_brief,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

VALID_ROLES = ["hook", "ethos", "pathos", "logos", "synthesis", "recap", "transition"]

REQUIRED_BRIEF_FIELDS = [
    "slug",
    "title",
    "content_goal",
    "visual_approach",
    "visual_pattern",
    "rhetorical_role",
    "design_invariants",
    "user_recommendations",
    "group_id",
]


def _minimal_brief(
    slug: str = "intro_slide",
    group_id: str = "group_01",
    rhetorical_role: str = "hook",
) -> dict:
    """Return a minimal valid brief dict."""
    return {
        "slug": slug,
        "title": "Introduction",
        "content_goal": "Set the scene",
        "visual_approach": "Full-bleed photograph",
        "visual_pattern": "Title + subtitle",
        "rhetorical_role": rhetorical_role,
        "design_invariants": ["No more than 20 words"],
        "user_recommendations": "Keep it bold",
        "group_id": group_id,
    }


def _setup_briefs_dir(project_root: Path) -> Path:
    """Create .debrief/briefs/ and return its path."""
    briefs = project_root / ".debrief" / "briefs"
    briefs.mkdir(parents=True, exist_ok=True)
    return briefs


def _write_ledger_entries(project_root: Path, count: int) -> None:
    """Write *count* entries to ledger.jsonl via append_ledger_entry."""
    debrief = project_root / ".debrief"
    debrief.mkdir(parents=True, exist_ok=True)
    for i in range(count):
        append_ledger_entry(
            project_root,
            role="consultant",
            content=f"entry {i}",
            group_id="group_01",
        )


# ---------------------------------------------------------------------------
# validate_slide_brief — BC-5.1
# ---------------------------------------------------------------------------


class TestValidateSlideBrief:
    def test_accepts_valid_brief_with_all_fields(self) -> None:
        brief = _minimal_brief()
        # Should not raise
        validate_slide_brief(brief)

    @pytest.mark.parametrize("role", VALID_ROLES)
    def test_accepts_each_valid_rhetorical_role(self, role: str) -> None:
        brief = _minimal_brief(rhetorical_role=role)
        validate_slide_brief(brief)

    def test_raises_value_error_for_invalid_rhetorical_role(self) -> None:
        brief = _minimal_brief(rhetorical_role="intro")
        with pytest.raises(ValueError):
            validate_slide_brief(brief)

    def test_raises_value_error_for_empty_rhetorical_role(self) -> None:
        brief = _minimal_brief(rhetorical_role="")
        with pytest.raises(ValueError):
            validate_slide_brief(brief)

    def test_raises_value_error_for_conclusion_role(self) -> None:
        brief = _minimal_brief(rhetorical_role="conclusion")
        with pytest.raises(ValueError):
            validate_slide_brief(brief)

    @pytest.mark.parametrize("field", REQUIRED_BRIEF_FIELDS)
    def test_raises_value_error_when_required_field_is_missing(
        self, field: str
    ) -> None:
        brief = _minimal_brief()
        del brief[field]
        with pytest.raises(ValueError):
            validate_slide_brief(brief)

    def test_error_message_mentions_missing_field(self) -> None:
        brief = _minimal_brief()
        del brief["content_goal"]
        with pytest.raises(ValueError, match="content_goal"):
            validate_slide_brief(brief)

    def test_error_message_mentions_invalid_rhetorical_role(self) -> None:
        brief = _minimal_brief(rhetorical_role="bad_role")
        with pytest.raises(ValueError, match="rhetorical_role|bad_role"):
            validate_slide_brief(brief)

    def test_raises_value_error_when_rhetorical_role_key_absent(self) -> None:
        brief = _minimal_brief()
        del brief["rhetorical_role"]
        with pytest.raises(ValueError):
            validate_slide_brief(brief)


# ---------------------------------------------------------------------------
# write_slide_brief — BC-5.1, BC-5.13
# ---------------------------------------------------------------------------


class TestWriteSlideBrief:
    def test_writes_brief_file_in_correct_location(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_slide_brief(
            project_root=tmp_path,
            group_id="group_01",
            slug="intro_slide",
            title="Introduction",
            content_goal="Set the scene",
            visual_approach="Full-bleed photograph",
            visual_pattern="Title + subtitle",
            rhetorical_role="hook",
            design_invariants=["No more than 20 words"],
            user_recommendations="Keep it bold",
        )
        expected = tmp_path / ".debrief" / "briefs" / "group_01_intro_slide.json"
        assert expected.exists()

    def test_written_brief_is_valid_json(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_slide_brief(
            project_root=tmp_path,
            group_id="group_01",
            slug="methods_overview",
            title="Methods",
            content_goal="Describe approach",
            visual_approach="Diagram",
            visual_pattern="Content-heavy",
            rhetorical_role="logos",
            design_invariants=["Use arrows"],
            user_recommendations="Be precise",
        )
        path = tmp_path / ".debrief" / "briefs" / "group_01_methods_overview.json"
        data = json.loads(path.read_text())
        assert isinstance(data, dict)

    def test_brief_contains_all_nine_required_fields(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_slide_brief(
            project_root=tmp_path,
            group_id="group_01",
            slug="results_slide",
            title="Results",
            content_goal="Show findings",
            visual_approach="Bar chart",
            visual_pattern="Data exhibit",
            rhetorical_role="logos",
            design_invariants=["Annotate bars"],
            user_recommendations="Highlight p-values",
        )
        path = tmp_path / ".debrief" / "briefs" / "group_01_results_slide.json"
        data = json.loads(path.read_text())
        for field in REQUIRED_BRIEF_FIELDS:
            assert field in data, f"Missing required field: {field}"

    def test_brief_persists_correct_field_values(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_slide_brief(
            project_root=tmp_path,
            group_id="group_02",
            slug="discussion_slide",
            title="Discussion",
            content_goal="Interpret results",
            visual_approach="Text layout",
            visual_pattern="Key points",
            rhetorical_role="synthesis",
            design_invariants=["Max 3 bullets"],
            user_recommendations="Be concise",
        )
        path = tmp_path / ".debrief" / "briefs" / "group_02_discussion_slide.json"
        data = json.loads(path.read_text())
        assert data["slug"] == "discussion_slide"
        assert data["group_id"] == "group_02"
        assert data["rhetorical_role"] == "synthesis"
        assert data["title"] == "Discussion"

    def test_raises_value_error_for_invalid_rhetorical_role(
        self, tmp_path: Path
    ) -> None:
        _setup_briefs_dir(tmp_path)
        with pytest.raises(ValueError):
            write_slide_brief(
                project_root=tmp_path,
                group_id="group_01",
                slug="bad_slide",
                title="Bad",
                content_goal="Test",
                visual_approach="None",
                visual_pattern="None",
                rhetorical_role="invalid_role",
                design_invariants=[],
                user_recommendations="",
            )

    def test_raises_value_error_for_slug_not_starting_with_letter(
        self, tmp_path: Path
    ) -> None:
        _setup_briefs_dir(tmp_path)
        with pytest.raises(ValueError):
            write_slide_brief(
                project_root=tmp_path,
                group_id="group_01",
                slug="1_bad_slug",
                title="Bad",
                content_goal="Test",
                visual_approach="None",
                visual_pattern="None",
                rhetorical_role="hook",
                design_invariants=[],
                user_recommendations="",
            )

    def test_raises_value_error_for_slug_ending_with_underscore(
        self, tmp_path: Path
    ) -> None:
        _setup_briefs_dir(tmp_path)
        with pytest.raises(ValueError):
            write_slide_brief(
                project_root=tmp_path,
                group_id="group_01",
                slug="bad_slug_",
                title="Bad",
                content_goal="Test",
                visual_approach="None",
                visual_pattern="None",
                rhetorical_role="hook",
                design_invariants=[],
                user_recommendations="",
            )

    def test_raises_value_error_for_slug_with_uppercase_letters(
        self, tmp_path: Path
    ) -> None:
        _setup_briefs_dir(tmp_path)
        with pytest.raises(ValueError):
            write_slide_brief(
                project_root=tmp_path,
                group_id="group_01",
                slug="BadSlug",
                title="Bad",
                content_goal="Test",
                visual_approach="None",
                visual_pattern="None",
                rhetorical_role="hook",
                design_invariants=[],
                user_recommendations="",
            )

    def test_write_is_atomic_no_tmp_file_remains(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_slide_brief(
            project_root=tmp_path,
            group_id="group_01",
            slug="atomic_slide",
            title="Atomic",
            content_goal="Test atomicity",
            visual_approach="Plain",
            visual_pattern="Simple",
            rhetorical_role="hook",
            design_invariants=[],
            user_recommendations="",
        )
        briefs_dir = tmp_path / ".debrief" / "briefs"
        tmp_files = list(briefs_dir.glob("*.tmp"))
        assert tmp_files == [], f"Unexpected .tmp files: {tmp_files}"

    def test_backup_flag_is_persisted_when_true(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_slide_brief(
            project_root=tmp_path,
            group_id="backup_01",
            slug="backup_slide",
            title="Backup",
            content_goal="Extra content",
            visual_approach="Plain",
            visual_pattern="Simple",
            rhetorical_role="recap",
            design_invariants=[],
            user_recommendations="",
            backup=True,
        )
        path = tmp_path / ".debrief" / "briefs" / "backup_01_backup_slide.json"
        data = json.loads(path.read_text())
        assert data.get("backup") is True

    def test_backup_flag_defaults_to_false(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_slide_brief(
            project_root=tmp_path,
            group_id="group_01",
            slug="no_backup_slide",
            title="No Backup",
            content_goal="Normal slide",
            visual_approach="Plain",
            visual_pattern="Simple",
            rhetorical_role="ethos",
            design_invariants=[],
            user_recommendations="",
        )
        path = tmp_path / ".debrief" / "briefs" / "group_01_no_backup_slide.json"
        data = json.loads(path.read_text())
        # backup should be absent or False
        assert not data.get("backup", False)

    @pytest.mark.parametrize("role", VALID_ROLES)
    def test_write_succeeds_for_each_valid_rhetorical_role(
        self, tmp_path: Path, role: str
    ) -> None:
        _setup_briefs_dir(tmp_path)
        slug = f"slide_{role}"
        write_slide_brief(
            project_root=tmp_path,
            group_id="group_01",
            slug=slug,
            title=role.capitalize(),
            content_goal="Test",
            visual_approach="Plain",
            visual_pattern="Simple",
            rhetorical_role=role,
            design_invariants=[],
            user_recommendations="",
        )
        path = tmp_path / ".debrief" / "briefs" / f"group_01_{slug}.json"
        assert path.exists()


# ---------------------------------------------------------------------------
# write_group_manifest — BC-5.2, BC-5.3, BC-5.14
# ---------------------------------------------------------------------------


class TestWriteGroupManifest:
    def test_writes_manifest_file_in_correct_location(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_group_manifest(
            project_root=tmp_path,
            group_id="group_01",
            slide_slugs=["slide_a", "slide_b"],
        )
        manifest_path = tmp_path / ".debrief" / "briefs" / "group_01_MANIFEST.json"
        assert manifest_path.exists()

    def test_manifest_is_valid_json(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_group_manifest(
            project_root=tmp_path,
            group_id="group_01",
            slide_slugs=["slide_a"],
        )
        path = tmp_path / ".debrief" / "briefs" / "group_01_MANIFEST.json"
        data = json.loads(path.read_text())
        assert isinstance(data, dict)

    def test_manifest_contains_group_id_field(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_group_manifest(
            project_root=tmp_path,
            group_id="group_02",
            slide_slugs=["slide_x"],
        )
        path = tmp_path / ".debrief" / "briefs" / "group_02_MANIFEST.json"
        data = json.loads(path.read_text())
        assert data["group_id"] == "group_02"

    def test_manifest_slide_count_matches_slug_list_length(
        self, tmp_path: Path
    ) -> None:
        _setup_briefs_dir(tmp_path)
        slugs = ["slide_a", "slide_b", "slide_c"]
        write_group_manifest(
            project_root=tmp_path,
            group_id="group_01",
            slide_slugs=slugs,
        )
        path = tmp_path / ".debrief" / "briefs" / "group_01_MANIFEST.json"
        data = json.loads(path.read_text())
        assert data["slide_count"] == len(slugs)

    def test_manifest_slide_count_for_single_slug(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_group_manifest(
            project_root=tmp_path,
            group_id="group_01",
            slide_slugs=["only_slide"],
        )
        path = tmp_path / ".debrief" / "briefs" / "group_01_MANIFEST.json"
        data = json.loads(path.read_text())
        assert data["slide_count"] == 1

    def test_manifest_slide_count_for_empty_slug_list(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_group_manifest(
            project_root=tmp_path,
            group_id="group_01",
            slide_slugs=[],
        )
        path = tmp_path / ".debrief" / "briefs" / "group_01_MANIFEST.json"
        data = json.loads(path.read_text())
        assert data["slide_count"] == 0

    def test_manifest_slugs_field_matches_input(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        slugs = ["first_slide", "second_slide"]
        write_group_manifest(
            project_root=tmp_path,
            group_id="group_01",
            slide_slugs=slugs,
        )
        path = tmp_path / ".debrief" / "briefs" / "group_01_MANIFEST.json"
        data = json.loads(path.read_text())
        assert data["slugs"] == slugs

    def test_manifest_contains_dispatched_at_timestamp(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_group_manifest(
            project_root=tmp_path,
            group_id="group_01",
            slide_slugs=["slide_a"],
        )
        path = tmp_path / ".debrief" / "briefs" / "group_01_MANIFEST.json"
        data = json.loads(path.read_text())
        assert "dispatched_at" in data
        assert isinstance(data["dispatched_at"], str)
        assert len(data["dispatched_at"]) > 0

    def test_write_is_atomic_no_tmp_file_remains(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_group_manifest(
            project_root=tmp_path,
            group_id="group_01",
            slide_slugs=["slide_a", "slide_b"],
        )
        briefs_dir = tmp_path / ".debrief" / "briefs"
        tmp_files = list(briefs_dir.glob("*.tmp"))
        assert tmp_files == [], f"Unexpected .tmp files: {tmp_files}"

    def test_raises_value_error_for_invalid_group_id_format(
        self, tmp_path: Path
    ) -> None:
        _setup_briefs_dir(tmp_path)
        with pytest.raises(ValueError):
            write_group_manifest(
                project_root=tmp_path,
                group_id="group_1",  # missing zero-padding
                slide_slugs=["slide_a"],
            )

    def test_raises_value_error_for_group_id_without_prefix(
        self, tmp_path: Path
    ) -> None:
        _setup_briefs_dir(tmp_path)
        with pytest.raises(ValueError):
            write_group_manifest(
                project_root=tmp_path,
                group_id="01",
                slide_slugs=["slide_a"],
            )

    def test_raises_value_error_for_group_id_with_bad_prefix(
        self, tmp_path: Path
    ) -> None:
        _setup_briefs_dir(tmp_path)
        with pytest.raises(ValueError):
            write_group_manifest(
                project_root=tmp_path,
                group_id="slide_01",
                slide_slugs=["slide_a"],
            )

    def test_accepts_backup_group_id_format(self, tmp_path: Path) -> None:
        _setup_briefs_dir(tmp_path)
        write_group_manifest(
            project_root=tmp_path,
            group_id="backup_01",
            slide_slugs=["backup_slide"],
        )
        path = tmp_path / ".debrief" / "briefs" / "backup_01_MANIFEST.json"
        assert path.exists()


# ---------------------------------------------------------------------------
# append_ledger_entry — BC-5.4
# ---------------------------------------------------------------------------


class TestAppendLedgerEntry:
    def test_creates_ledger_file_on_first_append(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        append_ledger_entry(
            project_root=tmp_path,
            role="consultant",
            content="Hello",
        )
        ledger = tmp_path / ".debrief" / "ledger.jsonl"
        assert ledger.exists()

    def test_appended_entry_is_valid_json_line(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        append_ledger_entry(
            project_root=tmp_path,
            role="consultant",
            content="First entry",
        )
        ledger = tmp_path / ".debrief" / "ledger.jsonl"
        lines = [line for line in ledger.read_text().splitlines() if line.strip()]
        assert len(lines) == 1
        entry = json.loads(lines[0])
        assert isinstance(entry, dict)

    def test_appended_entry_contains_required_fields(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        append_ledger_entry(
            project_root=tmp_path,
            role="user",
            content="User message",
            group_id="group_01",
            slug="intro_slide",
            event="group_start",
        )
        ledger = tmp_path / ".debrief" / "ledger.jsonl"
        lines = [line for line in ledger.read_text().splitlines() if line.strip()]
        entry = json.loads(lines[0])
        assert "timestamp" in entry
        assert "role" in entry
        assert "content" in entry
        assert "metadata" in entry

    def test_entry_role_and_content_match_arguments(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        append_ledger_entry(
            project_root=tmp_path,
            role="consultant",
            content="Decision made",
        )
        ledger = tmp_path / ".debrief" / "ledger.jsonl"
        lines = [line for line in ledger.read_text().splitlines() if line.strip()]
        entry = json.loads(lines[0])
        assert entry["role"] == "consultant"
        assert entry["content"] == "Decision made"

    def test_metadata_fields_are_persisted(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        append_ledger_entry(
            project_root=tmp_path,
            role="consultant",
            content="Group started",
            group_id="group_02",
            slug="results_slide",
            event="group_start",
        )
        ledger = tmp_path / ".debrief" / "ledger.jsonl"
        lines = [line for line in ledger.read_text().splitlines() if line.strip()]
        entry = json.loads(lines[0])
        assert entry["metadata"]["group_id"] == "group_02"
        assert entry["metadata"]["slug"] == "results_slide"
        assert entry["metadata"]["event"] == "group_start"

    def test_metadata_optional_fields_default_to_none(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        append_ledger_entry(
            project_root=tmp_path,
            role="consultant",
            content="No metadata",
        )
        ledger = tmp_path / ".debrief" / "ledger.jsonl"
        lines = [line for line in ledger.read_text().splitlines() if line.strip()]
        entry = json.loads(lines[0])
        assert entry["metadata"]["group_id"] is None
        assert entry["metadata"]["slug"] is None
        assert entry["metadata"]["event"] is None

    def test_multiple_appends_add_multiple_lines(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        for i in range(5):
            append_ledger_entry(
                project_root=tmp_path,
                role="consultant",
                content=f"entry {i}",
            )
        ledger = tmp_path / ".debrief" / "ledger.jsonl"
        lines = [line for line in ledger.read_text().splitlines() if line.strip()]
        assert len(lines) == 5

    def test_does_not_truncate_existing_entries(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        for i in range(3):
            append_ledger_entry(
                project_root=tmp_path,
                role="consultant",
                content=f"entry {i}",
            )
        # Each prior entry should still be present
        ledger = tmp_path / ".debrief" / "ledger.jsonl"
        lines = [line for line in ledger.read_text().splitlines() if line.strip()]
        assert len(lines) == 3
        contents = [json.loads(ln)["content"] for ln in lines]
        assert "entry 0" in contents
        assert "entry 2" in contents

    def test_entry_order_is_preserved(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        messages = ["alpha", "beta", "gamma"]
        for msg in messages:
            append_ledger_entry(
                project_root=tmp_path,
                role="consultant",
                content=msg,
            )
        ledger = tmp_path / ".debrief" / "ledger.jsonl"
        lines = [line for line in ledger.read_text().splitlines() if line.strip()]
        contents = [json.loads(ln)["content"] for ln in lines]
        assert contents == messages

    def test_timestamp_field_is_non_empty_string(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        append_ledger_entry(
            project_root=tmp_path,
            role="consultant",
            content="ts check",
        )
        ledger = tmp_path / ".debrief" / "ledger.jsonl"
        lines = [line for line in ledger.read_text().splitlines() if line.strip()]
        entry = json.loads(lines[0])
        assert isinstance(entry["timestamp"], str)
        assert len(entry["timestamp"]) > 0


# ---------------------------------------------------------------------------
# compact_ledger — BC-5.5, BC-5.6
# ---------------------------------------------------------------------------


class TestCompactLedger:
    def test_compaction_creates_archive_file(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        archive = debrief / "ledger_compact_001.jsonl"
        assert archive.exists()

    def test_archive_contains_all_original_entries(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        archive = debrief / "ledger_compact_001.jsonl"
        lines = [line for line in archive.read_text().splitlines() if line.strip()]
        assert len(lines) == 101

    def test_new_ledger_has_exactly_one_summary_entry(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        ledger = debrief / "ledger.jsonl"
        lines = [line for line in ledger.read_text().splitlines() if line.strip()]
        assert len(lines) == 1

    def test_summary_entry_is_valid_json(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        ledger = debrief / "ledger.jsonl"
        lines = [line for line in ledger.read_text().splitlines() if line.strip()]
        summary = json.loads(lines[0])
        assert isinstance(summary, dict)

    def test_second_compaction_increments_archive_counter(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        # First compaction
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        assert (debrief / "ledger_compact_001.jsonl").exists()
        # Second compaction: write 101 more entries into the new ledger
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        assert (debrief / "ledger_compact_002.jsonl").exists()

    def test_second_compaction_produces_only_one_summary_in_ledger(
        self, tmp_path: Path
    ) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        # Second round
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        ledger = debrief / "ledger.jsonl"
        lines = [line for line in ledger.read_text().splitlines() if line.strip()]
        assert len(lines) == 1

    def test_archive_naming_uses_three_digit_zero_padded_counter(
        self, tmp_path: Path
    ) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        archive = debrief / "ledger_compact_001.jsonl"
        assert archive.exists(), "Archive must be named ledger_compact_001.jsonl"

    def test_pre_existing_archive_skips_to_next_counter(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        # Pre-seed an archive to simulate prior compaction
        (debrief / "ledger_compact_001.jsonl").write_text(
            '{"role":"system","content":"old"}\n'
        )
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        assert (debrief / "ledger_compact_002.jsonl").exists()

    def test_archive_entries_are_each_valid_json(self, tmp_path: Path) -> None:
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        archive = debrief / "ledger_compact_001.jsonl"
        for raw_line in archive.read_text().splitlines():
            if raw_line.strip():
                parsed = json.loads(raw_line)
                assert isinstance(parsed, dict)

    def test_summary_entry_role_is_system(self, tmp_path: Path) -> None:
        """BC-5.5: the single remaining entry after compaction has role
        'system'."""
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        ledger = debrief / "ledger.jsonl"
        lines = [ln for ln in ledger.read_text().splitlines() if ln.strip()]
        summary = json.loads(lines[0])
        assert summary["role"] == "system"

    def test_summary_entry_metadata_event_is_compaction(
        self, tmp_path: Path
    ) -> None:
        """BC-5.5: the summary entry's metadata.event field is 'compaction'."""
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        ledger = debrief / "ledger.jsonl"
        lines = [ln for ln in ledger.read_text().splitlines() if ln.strip()]
        summary = json.loads(lines[0])
        assert summary.get("metadata", {}).get("event") == "compaction"

    def test_third_compaction_creates_ledger_compact_003(
        self, tmp_path: Path
    ) -> None:
        """BC-5.6: archive counter increments monotonically past 002."""
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        # Pre-seed two archives so the next index must be 003
        (debrief / "ledger_compact_001.jsonl").write_text(
            '{"role":"system","content":"old1"}\n'
        )
        (debrief / "ledger_compact_002.jsonl").write_text(
            '{"role":"system","content":"old2"}\n'
        )
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        assert (debrief / "ledger_compact_003.jsonl").exists()


# ---------------------------------------------------------------------------
# append_ledger_entry — BC-5.4 (pre-populated ledger not truncated)
# ---------------------------------------------------------------------------


class TestAppendLedgerEntryPrePopulated:
    def test_does_not_truncate_externally_written_content(
        self, tmp_path: Path
    ) -> None:
        """BC-5.4: append_ledger_entry must not truncate content written to the
        ledger by an external process before the first call in this session."""
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        ledger_path = debrief / "ledger.jsonl"
        prior_entry = {
            "timestamp": "2026-01-01T00:00:00+00:00",
            "role": "system",
            "content": "prior session entry",
            "metadata": {
                "group_id": None,
                "slug": None,
                "event": "compaction",
            },
        }
        ledger_path.write_text(
            json.dumps(prior_entry, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        # Now append a new entry via the library function
        append_ledger_entry(
            project_root=tmp_path,
            role="consultant",
            content="new session entry",
        )
        lines = [
            ln for ln in ledger_path.read_text().splitlines() if ln.strip()
        ]
        # Both the prior entry and the new one must be present
        assert len(lines) == 2
        first = json.loads(lines[0])
        assert first["content"] == "prior session entry"
        second = json.loads(lines[1])
        assert second["content"] == "new session entry"


# ---------------------------------------------------------------------------
# write_slide_brief — BC-5.13 (slug max length)
# ---------------------------------------------------------------------------


class TestWriteSlideBriefSlugLength:
    def test_raises_value_error_for_slug_exceeding_50_characters(
        self, tmp_path: Path
    ) -> None:
        """BC-5.13: slug regex ^[a-z][a-z0-9_]{0,49}$ caps total length at
        50 chars.  A 51-character slug must be rejected."""
        _setup_briefs_dir(tmp_path)
        # 51 lowercase letters: 'a' + 50 * 'b'
        long_slug = "a" + "b" * 50
        assert len(long_slug) == 51
        with pytest.raises(ValueError):
            write_slide_brief(
                project_root=tmp_path,
                group_id="group_01",
                slug=long_slug,
                title="Too Long",
                content_goal="Test",
                visual_approach="Plain",
                visual_pattern="Simple",
                rhetorical_role="hook",
                design_invariants=[],
                user_recommendations="",
            )

    def test_accepts_slug_of_exactly_50_characters(
        self, tmp_path: Path
    ) -> None:
        """BC-5.13: a slug of exactly 50 characters is at the boundary and
        must be accepted."""
        _setup_briefs_dir(tmp_path)
        # 50 lowercase letters: 'a' + 49 * 'b'
        max_slug = "a" + "b" * 49
        assert len(max_slug) == 50
        write_slide_brief(
            project_root=tmp_path,
            group_id="group_01",
            slug=max_slug,
            title="Max Length",
            content_goal="Test",
            visual_approach="Plain",
            visual_pattern="Simple",
            rhetorical_role="hook",
            design_invariants=[],
            user_recommendations="",
        )
        expected = (
            tmp_path / ".debrief" / "briefs" / f"group_01_{max_slug}.json"
        )
        assert expected.exists()


# ---------------------------------------------------------------------------
# BC-5.7: ledger module must not write deck_state.json or debrief_state.json
# ---------------------------------------------------------------------------


class TestNoStateFileWrites:
    def test_append_ledger_entry_does_not_write_state_files(
        self, tmp_path: Path
    ) -> None:
        """BC-5.7: append_ledger_entry must not create deck_state.json or
        debrief_state.json."""
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        append_ledger_entry(
            project_root=tmp_path,
            role="consultant",
            content="state check",
        )
        assert not (tmp_path / "deck_state.json").exists()
        assert not (tmp_path / "debrief_state.json").exists()

    def test_write_slide_brief_does_not_write_state_files(
        self, tmp_path: Path
    ) -> None:
        """BC-5.7: write_slide_brief must not create deck_state.json or
        debrief_state.json."""
        _setup_briefs_dir(tmp_path)
        write_slide_brief(
            project_root=tmp_path,
            group_id="group_01",
            slug="state_check_slide",
            title="State Check",
            content_goal="Verify no state write",
            visual_approach="Plain",
            visual_pattern="Simple",
            rhetorical_role="hook",
            design_invariants=[],
            user_recommendations="",
        )
        assert not (tmp_path / "deck_state.json").exists()
        assert not (tmp_path / "debrief_state.json").exists()

    def test_write_group_manifest_does_not_write_state_files(
        self, tmp_path: Path
    ) -> None:
        """BC-5.7: write_group_manifest must not create deck_state.json or
        debrief_state.json."""
        _setup_briefs_dir(tmp_path)
        write_group_manifest(
            project_root=tmp_path,
            group_id="group_01",
            slide_slugs=["slide_a"],
        )
        assert not (tmp_path / "deck_state.json").exists()
        assert not (tmp_path / "debrief_state.json").exists()

    def test_compact_ledger_does_not_write_state_files(
        self, tmp_path: Path
    ) -> None:
        """BC-5.7: compact_ledger must not create deck_state.json or
        debrief_state.json."""
        debrief = tmp_path / ".debrief"
        debrief.mkdir(parents=True)
        _write_ledger_entries(tmp_path, 101)
        compact_ledger(tmp_path)
        assert not (tmp_path / "deck_state.json").exists()
        assert not (tmp_path / "debrief_state.json").exists()
