# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Carlo Fusco and Leonardo Restivo
"""Regression tests for BUG-AUDIT-15.

Three drifts in how the project directory tree and deliverable folders were
produced — all rooted in "the agent decides", which is non-deterministic:

1. **Init gap.** Five canonical directories from spec section 3
   (``.debrief/``, ``.debrief/draft/``, ``.debrief/draft/preview_slides/``,
   ``.debrief/draft/preview_images/``, and ``output/``) were missing from
   ``launcher.py:_REQUIRED_DIRS``. The Stylist agent was told to write to
   ``.debrief/draft/preview_slides/*.html`` with no mkdir hint and no
   upstream code creating the directory; success depended on Claude Code's
   ``Write`` tool implicitly mkdir-ing parents.
2. **Re-entry gap.** Cleanup operations remove canonical directories during
   normal operation (style-lock, ``skill_reset``, ``skill_quit``). The
   ``debrief`` bare-invocation arm only called ``ensure_settings`` which
   self-heals settings but does not re-scaffold directories.
3. **Stale skill + LLM-driven folder name.** ``commands/export.md``
   described a removed PPTX/LibreOffice flow with output under ``exports/``
   while the actual code uses Playwright into ``output/<presentation_folder>/``.
   The ``<presentation_folder>`` name was generated by the Consultant LLM
   during the export ordering dialog with no code-side enforcement of the
   spec section 24.10 ``<YYYY_MM_DD>_<shortened_title>`` format.

This file enforces all three legs:

- BC-3.9 / BC-3.14: ``_REQUIRED_DIRS`` contains all 15 canonical entries;
  ``create_project_structure`` produces them; ``ensure_project`` orchestrator
  composes ``create_project_structure`` with ``ensure_project_settings`` and
  is idempotent and additive (does not clobber existing deliverable folders).
- ``bin/debrief`` bare-invocation arm calls ``ensure_project`` not
  ``ensure_settings``.
- ``commands/export.md`` is current-truth, not stale.
- BC-4.7c: ``propose_presentation_folder_name`` returns the spec-canonical
  format, reuses ``sanitize_identifier``, and ``main_prepare`` injects the
  ``## Proposed Presentation Folder`` section for export-dialog actions and
  NOT for other actions.

See ``spec/stakeholder_spec.md`` Bug Catalog entry BUG-AUDIT-15.
"""

from __future__ import annotations

import json
import re
import shutil
import sys
from datetime import date
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Dual-layout sys.path setup — matches BUG-AUDIT-13 / -14 pattern.
# ---------------------------------------------------------------------------

_REGRESSIONS_DIR = Path(__file__).resolve().parent
_TESTS_DIR = _REGRESSIONS_DIR.parent
_PROJECT_ROOT = _TESTS_DIR.parent


def _module_dir_for(stem: str, workspace_unit: str) -> Path:
    """Locate the directory containing ``<stem>.py`` for both layouts."""
    workspace = _PROJECT_ROOT / "src" / workspace_unit
    delivered = _PROJECT_ROOT / "src" / "debrief"
    for candidate in (workspace, delivered):
        if (candidate / f"{stem}.py").exists():
            return candidate
    raise FileNotFoundError(
        f"Could not find {stem}.py under {workspace} or {delivered}"
    )


# Set up sys.path for launcher, routing, and debrief_state imports.
for _stem, _unit in [
    ("launcher", "unit_3"),
    ("routing", "unit_4"),
    ("debrief_state", "unit_2"),
]:
    _dir = _module_dir_for(_stem, _unit)
    if str(_dir) not in sys.path:
        sys.path.insert(0, str(_dir))

import debrief_state  # noqa: E402
import launcher  # noqa: E402
import routing  # noqa: E402


def _bin_debrief_path() -> Path:
    workspace = _PROJECT_ROOT / "src" / "unit_1" / "bin" / "debrief"
    delivered = _PROJECT_ROOT / "bin" / "debrief"
    for candidate in (workspace, delivered):
        if candidate.exists():
            return candidate
    raise FileNotFoundError(
        f"Could not find bin/debrief at {workspace} or {delivered}"
    )


def _commands_export_md_path() -> Path:
    workspace = _PROJECT_ROOT / "src" / "unit_1" / "commands" / "export.md"
    delivered = _PROJECT_ROOT / "commands" / "export.md"
    for candidate in (workspace, delivered):
        if candidate.exists():
            return candidate
    raise FileNotFoundError(
        f"Could not find commands/export.md at {workspace} or {delivered}"
    )


_PROPOSED_FOLDER_FENCE_RE = re.compile(
    r"## Proposed Presentation Folder.*?```\n(.*?)\n```",
    re.DOTALL,
)


def _make_synthetic_deck_state(project_name: str = "lab_meeting") -> dict:
    return {
        "project_name": project_name,
        "created_at": "2026-04-15T10:00:00Z",
        "archetype": "lab_meeting",
        "style_locked": True,
        "closing_slide": None,
        "slides": [],
        "presentations": [],
    }


# ---------------------------------------------------------------------------
# Leg 1-5 — directory tree determinism.
# ---------------------------------------------------------------------------


class TestBugAudit15CanonicalTreeDeterministic:
    """BC-3.9 / BC-3.14 / BUG-AUDIT-15 — the canonical project tree exists
    at every moment of the project's life: created at init, re-scaffolded
    on every bare ``debrief`` re-entry, never relies on agent mkdir.
    """

    def test_required_dirs_includes_debrief_root(self) -> None:
        assert ".debrief" in launcher._REQUIRED_DIRS, (
            "BUG-AUDIT-15 / BC-3.9: _REQUIRED_DIRS must contain `.debrief` "
            "as an explicit entry (not just implicit via .debrief/briefs)."
        )

    def test_required_dirs_includes_debrief_draft(self) -> None:
        assert ".debrief/draft" in launcher._REQUIRED_DIRS, (
            "BUG-AUDIT-15: _REQUIRED_DIRS must contain `.debrief/draft`."
        )

    def test_required_dirs_includes_preview_slides(self) -> None:
        assert ".debrief/draft/preview_slides" in launcher._REQUIRED_DIRS, (
            "BUG-AUDIT-15: _REQUIRED_DIRS must contain "
            "`.debrief/draft/preview_slides`. The Stylist writes preview "
            "HTML here per REQ-STYLE-10."
        )

    def test_required_dirs_includes_preview_images(self) -> None:
        assert ".debrief/draft/preview_images" in launcher._REQUIRED_DIRS, (
            "BUG-AUDIT-15: _REQUIRED_DIRS must contain "
            "`.debrief/draft/preview_images`. The Stylist writes preview "
            "PNGs here per REQ-STYLE-10."
        )

    def test_required_dirs_includes_output_root(self) -> None:
        assert "output" in launcher._REQUIRED_DIRS, (
            "BUG-AUDIT-15: _REQUIRED_DIRS must contain `output` as an "
            "explicit entry, not just implicit via output/screenshots."
        )

    def test_create_project_structure_creates_all_drifting_dirs(
        self, tmp_path: Path
    ) -> None:
        launcher.create_project_structure(tmp_path)
        drifting = [
            ".debrief",
            ".debrief/draft",
            ".debrief/draft/preview_slides",
            ".debrief/draft/preview_images",
            "output",
        ]
        for rel in drifting:
            assert (tmp_path / rel).is_dir(), (
                f"BUG-AUDIT-15 / BC-3.9: create_project_structure must "
                f"produce {rel!r} at init."
            )

    def test_ensure_project_orchestrator_calls_both_helpers(
        self, tmp_path: Path
    ) -> None:
        # plugin_root just needs to point somewhere real; the marketplace
        # path will be its parent. Using tmp_path itself avoids touching
        # the real plugin install.
        launcher.ensure_project(tmp_path, tmp_path)
        # Directories created by create_project_structure
        assert (tmp_path / ".debrief" / "draft").is_dir(), (
            "BC-3.14: ensure_project must run create_project_structure."
        )
        # Settings file created by ensure_project_settings
        assert (tmp_path / ".claude" / "settings.json").is_file(), (
            "BC-3.14: ensure_project must run ensure_project_settings, "
            "which creates `.claude/settings.json`."
        )

    def test_re_entry_after_draft_cleanup_restores_canonical_tree(
        self, tmp_path: Path
    ) -> None:
        # The user's exact scenario: cleanup (e.g., style-lock) removed
        # `.debrief/draft/`, then the user comes back via bare `debrief`.
        launcher.create_project_structure(tmp_path)
        shutil.rmtree(tmp_path / ".debrief" / "draft")
        assert not (tmp_path / ".debrief" / "draft").exists(), (
            "Pre-condition: simulated cleanup removed .debrief/draft/."
        )

        launcher.ensure_project(tmp_path, tmp_path)

        for rel in (
            ".debrief/draft",
            ".debrief/draft/preview_slides",
            ".debrief/draft/preview_images",
        ):
            assert (tmp_path / rel).is_dir(), (
                f"BC-3.14 / BUG-AUDIT-15: ensure_project re-entry must "
                f"restore {rel!r} after cleanup."
            )

    def test_ensure_project_is_idempotent(self, tmp_path: Path) -> None:
        launcher.ensure_project(tmp_path, tmp_path)
        # Second call must not raise.
        launcher.ensure_project(tmp_path, tmp_path)
        # Tree is still complete.
        for rel in launcher._REQUIRED_DIRS:
            assert (tmp_path / rel).is_dir()

    def test_bin_debrief_calls_ensure_project_not_ensure_settings(
        self,
    ) -> None:
        content = _bin_debrief_path().read_text(encoding="utf-8")
        # The bare-invocation arm now goes through ensure_project.
        assert "python -m debrief.launcher ensure_project" in content, (
            "BC-3.14: bin/debrief bare-invocation arm must call "
            "`python -m debrief.launcher ensure_project` so the canonical "
            "directory tree is restored on every re-entry."
        )
        # Negative sentinel: the bare arm does NOT call ensure_settings.
        # We allow the string `ensure_settings` to appear elsewhere (e.g.,
        # in a comment or in the new-project arm), but the active
        # invocation in the bare arm must use ensure_project. We check
        # by verifying ensure_project appears at least once and that any
        # ensure_settings invocation would be a regression.
        bare_arm_invocation = "python -m debrief.launcher ensure_settings"
        assert bare_arm_invocation not in content, (
            "BC-3.14 regression: bin/debrief no longer invokes "
            "`ensure_settings`. If you brought it back, the canonical "
            "directory tree is no longer re-scaffolded on re-entry — "
            "use `ensure_project` instead."
        )

    def test_existing_presentation_folder_survives_re_entry_re_scaffold(
        self, tmp_path: Path
    ) -> None:
        # REQ-EXPORT-3 contract: re-scaffolding must be additive. A
        # previously-produced deliverable folder must be preserved across
        # an ensure_project call.
        launcher.create_project_structure(tmp_path)
        deliverable_folder = tmp_path / "output" / "2026_04_15_lab_meeting"
        deliverable_folder.mkdir(parents=True)
        sentinel_pdf = deliverable_folder / "deck_v001.pdf"
        sentinel_pdf.write_bytes(b"fake-pdf-bytes")

        launcher.ensure_project(tmp_path, tmp_path)

        assert sentinel_pdf.is_file(), (
            "BC-3.14: ensure_project re-entry must NEVER remove or "
            "overwrite an existing deliverable folder. mkdir(exist_ok=True) "
            "is additive by construction; this test pins that contract."
        )
        assert sentinel_pdf.read_bytes() == b"fake-pdf-bytes", (
            "BC-3.14: re-entry must preserve deliverable file contents."
        )


# ---------------------------------------------------------------------------
# Leg 6 — commands/export.md is current-truth, not stale.
# ---------------------------------------------------------------------------


class TestBugAudit15CommandsExportMd:
    """BUG-AUDIT-15 Leg 6 — `commands/export.md` describes the current
    Playwright-based export, not the removed PPTX/LibreOffice flow.
    """

    def test_export_command_md_does_not_mention_legacy_paths(self) -> None:
        content = _commands_export_md_path().read_text(encoding="utf-8")
        # Negative sentinels for the stale content.
        legacy = ["python-pptx", "LibreOffice"]
        for token in legacy:
            assert token not in content, (
                f"BUG-AUDIT-15 Leg 6 regression: commands/export.md must "
                f"not mention legacy {token!r}; the actual export module "
                f"uses Playwright directly."
            )
        # `exports/` (with trailing slash) is the stale output path. The
        # current path is `output/<presentation_folder>/`. Allow `exports`
        # to appear as a substring of `output/`-related text, but reject
        # the standalone legacy path.
        assert " exports/" not in content and "to exports/" not in content, (
            "BUG-AUDIT-15 Leg 6 regression: commands/export.md must not "
            "describe output as going to `exports/`; the canonical path "
            "is `output/<presentation_folder>/` per REQ-EXPORT-3."
        )

    def test_export_command_md_documents_current_truth(self) -> None:
        content = _commands_export_md_path().read_text(encoding="utf-8")
        for token in (
            "Playwright",
            "<presentation_folder>",
            "output/",
            "deck_v",
        ):
            assert token in content, (
                f"BUG-AUDIT-15 Leg 6: commands/export.md must mention "
                f"{token!r} so the user-facing description matches the "
                f"actual export.py behavior."
            )

    def test_export_command_md_references_canonical_sources(self) -> None:
        content = _commands_export_md_path().read_text(encoding="utf-8")
        anchors = ("REQ-EXPORT-3", "§24.10", "REQ-LIFE-3")
        found = [a for a in anchors if a in content]
        assert found, (
            f"BUG-AUDIT-15 Leg 6: commands/export.md must reference at "
            f"least one of the canonical spec sources {anchors!r} so "
            f"future maintainers can trace the path back."
        )


# ---------------------------------------------------------------------------
# Leg 7 — deterministic deliverable-folder name proposal (BC-4.7c).
# ---------------------------------------------------------------------------


class _FakeDeckState:
    """Minimal stand-in for DeckState for proposal-helper tests."""

    def __init__(self, project_name: str) -> None:
        self.project_name = project_name


class TestBugAudit15ProposePresentationFolderName:
    """BC-4.7c / BUG-AUDIT-15 Leg 7 — the deliverable-folder name
    proposal is computed by code, not by the LLM.
    """

    def test_propose_format_with_fixed_date(self) -> None:
        result = routing.propose_presentation_folder_name(
            _FakeDeckState("lab_meeting"),
            today=date(2026, 4, 15),
        )
        assert result == "2026_04_15_lab_meeting", (
            f"BC-4.7c: propose_presentation_folder_name must return the "
            f"canonical `<YYYY_MM_DD>_<shortened_title>` format. Got: "
            f"{result!r}"
        )

    def test_propose_uses_canonical_sanitizer(self) -> None:
        # Spec section 24.10.1 worked example: "SVP Presentation" -> "svp_presentation".
        result = routing.propose_presentation_folder_name(
            _FakeDeckState("SVP Presentation"),
            today=date(2026, 4, 30),
        )
        assert result == "2026_04_30_svp_presentation", (
            f"BC-4.7c: the title portion must be produced by the canonical "
            f"sanitize_identifier (spec section 24.10.1) which lowercases "
            f"and replaces spaces with underscores. Got: {result!r}"
        )

    def test_propose_slugifies_unsafe_chars(self) -> None:
        result = routing.propose_presentation_folder_name(
            _FakeDeckState("My Project / Test!"),
            today=date(2026, 4, 15),
        )
        # Spec 24.10.1: lowercase, spaces and hyphens to underscores,
        # strip non-[a-z0-9_], collapse, strip edges.
        assert re.fullmatch(r"\d{4}_\d{2}_\d{2}_[a-z0-9_]+", result), (
            f"BC-4.7c: result must match the canonical regex. Got: {result!r}"
        )
        assert "/" not in result and "!" not in result, (
            f"BC-4.7c: unsafe path chars must be stripped. Got: {result!r}"
        )

    def test_propose_caps_length(self) -> None:
        result = routing.propose_presentation_folder_name(
            _FakeDeckState("a" * 200),
            today=date(2026, 4, 15),
        )
        # date prefix is 11 chars (`2026_04_15_`), title cap is 40 chars.
        # Total length must not exceed 51.
        assert len(result) <= 51, (
            f"BC-4.7c: total length must not exceed 51 chars (date + cap). "
            f"Got length {len(result)}: {result!r}"
        )

    def test_propose_falls_back_to_untitled_for_empty(self) -> None:
        result = routing.propose_presentation_folder_name(
            _FakeDeckState(""),
            today=date(2026, 4, 15),
        )
        assert result == "2026_04_15_untitled", (
            f"BC-4.7c: empty project_name must fall back to `untitled` per "
            f"spec section 24.10.1 step 7. Got: {result!r}"
        )

    def test_propose_uses_today_by_default(self) -> None:
        result = routing.propose_presentation_folder_name(
            _FakeDeckState("demo"),
            # No `today` argument — must default to date.today().
        )
        expected_prefix = date.today().strftime("%Y_%m_%d") + "_"
        assert result.startswith(expected_prefix), (
            f"BC-4.7c: missing `today` argument must default to "
            f"date.today(). Got: {result!r}"
        )


class TestBugAudit15PrepareInjectsProposedFolder:
    """BC-4.7c / BUG-AUDIT-15 Leg 7 — `main_prepare` injects the
    proposed-folder section for export-dialog actions.
    """

    def _project_with_deck_state(
        self, tmp_path: Path, project_name: str = "lab_meeting"
    ) -> Path:
        project = tmp_path / "project"
        (project / ".debrief").mkdir(parents=True)
        (project / "deck_state.json").write_text(
            json.dumps(_make_synthetic_deck_state(project_name)),
            encoding="utf-8",
        )
        return project

    def test_main_prepare_injects_section_for_export_confirm(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.delenv("CLAUDE_PLUGIN_ROOT", raising=False)
        project = self._project_with_deck_state(tmp_path)

        routing.main_prepare("finalization/export_confirm", project)
        content = (project / ".debrief" / "task_prompt.md").read_text(
            encoding="utf-8"
        )
        assert "## Proposed Presentation Folder" in content, (
            "BC-4.7c: the export-confirm action must trigger injection of "
            "the Proposed Presentation Folder section."
        )

    def test_main_prepare_injects_section_for_export_options(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.delenv("CLAUDE_PLUGIN_ROOT", raising=False)
        project = self._project_with_deck_state(tmp_path)

        routing.main_prepare("finalization/export_options", project)
        content = (project / ".debrief" / "task_prompt.md").read_text(
            encoding="utf-8"
        )
        assert "## Proposed Presentation Folder" in content, (
            "BC-4.7c: the export-options action must also trigger injection."
        )

    def test_injected_name_matches_propose_helper(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.delenv("CLAUDE_PLUGIN_ROOT", raising=False)
        project = self._project_with_deck_state(
            tmp_path, project_name="lab_meeting"
        )

        routing.main_prepare("finalization/export_confirm", project)
        content = (project / ".debrief" / "task_prompt.md").read_text(
            encoding="utf-8"
        )
        match = _PROPOSED_FOLDER_FENCE_RE.search(content)
        assert match, (
            "BC-4.7c: injected section must contain a fenced code block."
        )
        injected_name = match.group(1).strip()
        # Today's date prefix + sanitized project name.
        expected_prefix = date.today().strftime("%Y_%m_%d") + "_lab_meeting"
        assert injected_name == expected_prefix, (
            f"BC-4.7c: injected name must match propose_presentation_folder_name. "
            f"Got: {injected_name!r}, expected: {expected_prefix!r}"
        )

    def test_main_prepare_no_injection_for_non_export_action(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # Negative sentinel: production/red_green is not an export-dialog
        # action. The injection must NOT trigger.
        monkeypatch.delenv("CLAUDE_PLUGIN_ROOT", raising=False)
        project = self._project_with_deck_state(tmp_path)

        routing.main_prepare("production/red_green", project)
        content = (project / ".debrief" / "task_prompt.md").read_text(
            encoding="utf-8"
        )
        assert "## Proposed Presentation Folder" not in content, (
            "BC-4.7c: the Proposed Presentation Folder section must only "
            "be injected for export-dialog actions. A non-export action "
            "must NOT contain it — otherwise the injection is triggering "
            "too broadly."
        )

    def test_injected_section_cites_canonical_sources(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.delenv("CLAUDE_PLUGIN_ROOT", raising=False)
        project = self._project_with_deck_state(tmp_path)

        routing.main_prepare("finalization/export_confirm", project)
        content = (project / ".debrief" / "task_prompt.md").read_text(
            encoding="utf-8"
        )
        for token in ("BC-4.7c", "§24.10", "REQ-EXPORT-3"):
            assert token in content, (
                f"BC-4.7c: explainer paragraph must cite {token!r} so "
                f"future maintainers can trace the contract back."
            )

    def test_missing_deck_state_causes_hard_error(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # Export-dialog actions only fire after Phase 3; missing
        # deck_state.json at this point indicates state corruption and
        # main_prepare must hard-exit.
        monkeypatch.delenv("CLAUDE_PLUGIN_ROOT", raising=False)
        project = tmp_path / "project_no_deck"
        (project / ".debrief").mkdir(parents=True)
        # Deliberately do NOT write deck_state.json.

        with pytest.raises(SystemExit) as exc_info:
            routing.main_prepare("finalization/export_confirm", project)
        assert exc_info.value.code == 1, (
            "BC-4.7c / BUG-AUDIT-15: missing deck_state.json at export-"
            "dialog prepare time must cause hard exit with code 1, not "
            "silent omission of the proposal section."
        )
